# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(blank=True, max_length=64, null=True)),
                ('recording_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_spec', models.NullBooleanField()),
                ('defect', models.CharField(blank=True, choices=[('surface', 'surface'), ('position', 'position')], max_length=32, null=True)),
                ('quality', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('top_corner_left', models.IntegerField(blank=True, null=True)),
                ('top_corner_right', models.IntegerField(blank=True, null=True)),
                ('bot_corner_left', models.IntegerField(blank=True, null=True)),
                ('bot_corner_right', models.IntegerField(blank=True, null=True)),
                ('rotation_val', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='evaluation_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='displacement_detector_api.EvaluationResult'),
        ),
    ]
