# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displacement_detector_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisimage',
            name='picture_left_after',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='picture_left_before',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='picture_right_after',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='picture_right_before',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
