# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displacement_detector_api', '0002_auto_20190209_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisimage',
            name='date_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='date_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
