# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displacement_detector_api', '0003_auto_20190209_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisimage',
            name='recording_date',
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='bot_corner_left',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='bot_corner_right',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='defect',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('surface', 'surface'), ('position', 'position')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='top_corner_left',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='top_corner_right',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
