# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displacement_detector_api', '0004_auto_20190209_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisimage',
            name='evaluation_result',
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='bot_corner_left',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='bot_corner_right',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='defect',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('surface', 'surface'), ('position', 'position')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='in_spec',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='quality',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='rotation_val',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='top_corner_left',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='top_corner_right',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
