# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displacement_detector_api', '0005_auto_20190209_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisimage',
            name='bot_corner_left',
        ),
        migrations.RemoveField(
            model_name='analysisimage',
            name='bot_corner_right',
        ),
        migrations.RemoveField(
            model_name='analysisimage',
            name='top_corner_left',
        ),
        migrations.RemoveField(
            model_name='analysisimage',
            name='top_corner_right',
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='rotation_val_left',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='rotation_val_right',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='translation_val_left_x',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='translation_val_left_y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='translation_val_right_x',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='translation_val_right_y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
