# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displacement_detector_api', '0006_auto_20190210_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisimage',
            name='overlay_left',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='analysisimage',
            name='overlay_right',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
